{"uuid": "c762d1dc-66b3-4209-a10b-ea7d269ac288", "children": ["e8a8e417-42cd-49bd-843c-13caf615e0c9", "dbdf6a01-d761-40c5-8ae2-f2573a725697", "5b64e617-5970-4f5e-9935-71006a03fb54", "c7b0c52d-7bfc-45d8-891f-70b0af28237b", "202ae1c0-5e20-4992-b669-67d387a98fdb", "2b8e7f4e-1aa6-46dc-94f5-986c9edaefe4", "80516051-dc94-4ef6-ad10-97671e7c47c7", "876db58f-fa3d-4cba-b1c1-e247b38f6073", "d2cd11f3-173b-40c2-b8e8-91ce8ddd5c53", "8d98be81-f119-44b2-8a6d-08ac9ed8a36e", "44612a96-fd8b-4ed7-bac1-316f6b681cac", "183a12cb-8ffa-42e4-affe-cd1d0295da18"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "KeyError: 'data'\n", "trace": "  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\autoTest\\testcases\\cdn\\ctyun_console\\test_ctyun_log_user.py\", line 34, in setup_class\n    self.get_domain_list = self.log.get_ctyun_domain_list(self.console_host, self.workspaceId)\n  File \"D:\\autoTest\\bin\\createLogData.py\", line 136, in get_ctyun_domain_list\n    temp = body['data']['list']\n"}, "start": 1606461311886, "stop": 1606461311940}], "start": 1606461311886, "stop": 1606461312142}